#!/usr/bin/env bash
source "$COLOGEN_REFRESH_CONFIG/path.sh"

declare NEW_COLORSCHEME=""

change_colorscheme() {
    local -r input_path="$COLOGEN_REFRESH_SCHEMES/$1.yaml"
    local -r output_path="$COLOGEN_REFRESH_CURRENT_SCHEME"
    if [ -r "$input_path" ]
    then
        chmod +w $output_path
        cat $input_path > $output_path
        chmod -w $output_path
        return 0
    else
        echo "$1 not found"
        return 1
    fi
}

execute_all_targets() {
    chmod +r $COLOGEN_REFRESH_CURRENT_SCHEME
    for target in $(ls $COLOGEN_REFRESH_TARGETS); do
        echo "executing \"$target\"..."
        $COLOGEN_REFRESH_TARGETS/$target
    done
    chmod -r $COLOGEN_REFRESH_CURRENT_SCHEME
}

print_help() {
    echo "Usage:"
    echo "    $0                    # Refresh the configuration"
    echo "    $0 -c [COLORSCHEME]   # Change the color scheme"
    echo "    $0 -h                 # Print this help"
}

while getopts "hc:" arg; do
    case $arg in
    c)
        COLORSCHEME_CHANGE="TRUE"
        NEW_COLORSCHEME=$OPTARG
    ;;
    h)
        print_help
        exit 0
    ;;
    *)
        print_help
        exit 1
    ;;
    esac
done

if [ "$COLORSCHEME_CHANGE" == "TRUE" ]
then
    change_colorscheme $NEW_COLORSCHEME
    [ $? -eq 0 ] && execute_all_targets
else
    execute_all_targets
fi
