#!/usr/bin/env bash

export COLOGEN_REFRESH_CURRENT_SCHEME="$COLOGEN_REFRESH_CACHE/current.yaml"
export COLOGEN_REFRESH_SCHEMES="$COLOGEN_REFRESH_CONFIG/schemes"
export COLOGEN_REFRESH_TARGETS="$COLOGEN_REFRESH_CONFIG/targets"
export COLOGEN_REFRESH_TEMPLATES="$COLOGEN_REFRESH_CONFIG/templates"
