#!/usr/bin/env bash

bspc config normal_border_color     "#3c3836"
bspc config focused_border_color    "#7c6f64"
bspc config presel_feedback_color   "#fabd2f"
bspc config active_border_color     "#fabd2f"
