#!/usr/bin/env bash
source "$COLOGEN_REFRESH_CONFIG/source.sh"

bspc config normal_border_color     "$COLOR_GREY1"
bspc config focused_border_color    "$COLOR_GREY2"
bspc config presel_feedback_color   "$COLOR_YELLOW"
bspc config active_border_color     "$COLOR_YELLOW"
