#!/usr/bin/env bash

# Workspaces
bspc monitor -d 1 2 3 4 5 6

# Themes
bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Termite:floatingTerm state=floating rectangle=722x424+12+36
