#!/usr/bin/env sh
readonly desktopID=$1
readonly last_monitorID=$(bspc query -M -m)

# Focus to given desktop for all monitors
bspc query -M 2>/dev/null | while read -r monitorID; do
        bspc desktop -f "$monitorID:^$desktopID"
done

# Restore monitor focusing
bspc monitor -f "$last_monitorID"

# vim:ft=sh
# vim:wrap!
