#!/usr/bin/env sh
readonly direction=$1

bspc config pointer_follows_monitor true
# If no node for given direction,
# try focusing monitor of the direction
if ! bspc node -f $direction; then
    bspc monitor -f $direction
fi
bspc config pointer_follows_monitor false

# vim:ft=sh
# vim:wrap!
