#!/usr/bin/env sh

# Workspaces
bspc monitor ^1 -d 1 2 3 4 5 6
bspc monitor ^2 -d 1 2 3 4 5 6

# Themes
bspc config border_width 2
bspc config window_gap 12
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Performance
bspc config pointer_motion_interval 0

# Rules
bspc rule -a Alacritty:floatingTerm state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Thunar:floatingFileManager state=floating

