#!/usr/bin/env sh
readonly XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

install () {
    # cd to cli directory
    cd $(realpath $(dirname $0))
    cd $(git rev-parse --show-cdup)/cli

    # stow subpkgs
    stow -Svt $HOME mpd nvim tmux zsh

    # setup mpd directories (mpd)
    mkdir -p $HOME/.mpd/playlists
    mkdir -p $HOME/music

    # install vim-plug (nvim)
    sh -c 'curl -fLo $XDG_DATA_HOME/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    # install tmux-plugin-manager (tmux)
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm

    # reload zsh for install zinit (zsh)
    exec zsh
}

[ -x $(which stow) ] && install || stow

# vim:ft=sh
# vim:wrap!
